url: https://datajujitsuconsultants.github.io
baseurl: /datajujitsu-site/

# Site settings
title: Data Jujitsu
email: david@datajujitsuconsultants.com
description: "."


# Team names, titles and social links
people:
- name: David Springate
  pic: dave
  position: Owner and Chief consultant
  social:
    - title: twitter
      url: https://twitter.com/dataJujitsu
    - title: linkedin
      url: https://www.linkedin.com/in/daspringate/
    - title: github
      url: https://github.com/DASpringate
#    - title: stack-overflow
#      url: #

social:
  - title: twitter
    url: http://twitter.com/datajujitsu
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/DataJujitsu

# Postal address (add as many lines as necessary)
address:
  - line: 8 Grosvenor Square
  - line: Manchester, M33 6QU

# Build settings
markdown: kramdown
permalink: pretty


## Extra pages
include: ["_pages", "_services"]

## Blog

paginate: 5

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50
